import { useEffect, useMemo, useState } from 'react';
import { Archive, ClipboardList, Trophy } from 'lucide-react';
import { useAppStore } from '../store/app-store';
import { listGames } from '../lib/supabase';
import { computeStats } from '../lib/scoring';
import { formatDateTime, formatScore } from '../lib/format';
import type { Game, Match } from '../lib/types';

export function MatchesPage() {
  const { room, matches, players, playerName } = useAppStore();
  const ended = matches.filter((match) => match.status === 'ended');
  const [selected, setSelected] = useState<Match | null>(null);
  const [games, setGames] = useState<Game[]>([]);
  useEffect(() => { if (!selected || !room) { setGames([]); return; } void listGames(room.id, selected.id).then(setGames).catch(() => setGames([])); }, [selected, room]);
  const stats = useMemo(() => computeStats(players, games), [players, games]);
  if (ended.length === 0) return <div className="mx-auto flex min-h-[60vh] max-w-md flex-col items-center justify-center px-6 text-center"><div className="mb-4 flex h-20 w-20 items-center justify-center rounded-full border-2 border-dashed border-line"><Archive size={32} className="text-ink-muted" /></div><h2 className="font-display text-xl font-semibold">暂无历史场次</h2><p className="mt-2 text-sm text-ink-muted">在设置中结束当前场次后，这里会保留该场的积分和对局明细。</p></div>;
  return <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6"><header className="mb-5"><h1 className="font-display text-2xl font-bold tracking-wide">历史场次 <span className="ml-2 font-body text-xs font-normal text-ink-muted">MATCH ARCHIVE</span></h1></header><div className="grid gap-5 lg:grid-cols-[280px_1fr]"><aside className="space-y-2">{ended.map((match) => <button key={match.id} type="button" onClick={() => setSelected(match)} className={`w-full rounded-lg border p-3 text-left ${selected?.id === match.id ? 'border-primary bg-primary/10' : 'border-line bg-panel-2'}`}><div className="font-semibold">{match.name}</div><div className="mt-1 text-xs text-ink-muted">结束：{match.endedAt ? formatDateTime(match.endedAt) : '—'}</div></button>)}</aside><section className="tac-card p-5">{!selected ? <p className="py-10 text-center text-sm text-ink-muted">选择左侧场次查看积分和明细</p> : <><div className="mb-4 flex items-center gap-2"><Trophy size={18} className="text-primary" /><h2 className="font-display text-lg font-bold">{selected.name} · {games.length} 局</h2></div><div className="space-y-2">{stats.map((item, index) => <div key={item.player.id} className="flex items-center gap-3 rounded-lg bg-panel-2 px-3 py-2"><span className="num w-5 text-ink-muted">{index + 1}</span><span className="flex-1 font-semibold">{item.player.name}</span><span className="text-xs text-ink-muted">{item.games} 局 · {item.totalKills} 杀 · {item.wins} 鸡</span><span className={`num text-lg font-bold ${item.totalScore > 0 ? 'text-gain' : item.totalScore < 0 ? 'text-loss' : 'text-ink-muted'}`}>{formatScore(item.totalScore)}</span></div>)}</div><div className="mt-5 border-t border-line pt-4"><h3 className="mb-3 flex items-center gap-2 font-display text-sm font-bold"><ClipboardList size={15} className="text-primary" /> 对局明细</h3><div className="space-y-2">{games.map((game, index) => <div key={game.id} className="rounded-lg border border-line bg-panel-2 p-3"><div className="mb-2 text-xs text-ink-muted">第 {games.length - index} 局 · {formatDateTime(game.playedAt)}</div>{game.participantIds.map((id) => <div key={id} className="flex justify-between py-0.5 text-sm"><span>{playerName(id)} · {game.kills[id] ?? 0} 杀</span><span className="num">{formatScore(game.scores[id] ?? 0)}</span></div>)}</div>)}</div></div></>}</section></div></div>;
}
